sudo: required
services:
- docker
language: go
go:
- '1.10'
- '1.11'
go_import_path: openpitrix.io/runtime-provider-aws
script:
- make check
deploy:
- provider: script
  script: bash docker_push latest
  on:
    branch: master
    repo: openpitrix/runtime-provider-aws
- provider: script
  script: bash docker_push $TRAVIS_TAG
  on:
    tags: true
    repo: openpitrix/runtime-provider-aws